# Generated by Django 5.2.9 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Título do banner (para identificação no admin)",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        default="https://via.placeholder.com/800x300/FFE000/000000?text=Banner+Placeholder",
                        help_text="URL da imagem do banner (ex: https://exemplo.com/imagem.jpg)",
                        max_length=500,
                        verbose_name="URL da Imagem",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Se o banner está ativo e deve ser exibido",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Ordem de exibição (menor número aparece primeiro)",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
