# Generated by Django 5.2.9 on 2026-01-10 17:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbacatePayCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID do cliente na AbacatePay (ex: cust_12345)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadados adicionais do cliente",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuário associado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abacatepay_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente AbacatePay",
                "verbose_name_plural": "Clientes AbacatePay",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbacatePayBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID da cobrança na AbacatePay (ex: bill_12345667)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(
                        blank=True, help_text="URL para pagamento", max_length=500
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor da cobrança em reais",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Status da cobrança",
                        max_length=20,
                    ),
                ),
                (
                    "methods",
                    models.JSONField(
                        default=list,
                        help_text="Métodos de pagamento disponíveis (ex: ['PIX', 'CARD'])",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        default="ONE_TIME",
                        help_text="Frequência da cobrança (ONE_TIME, RECURRING, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "dev_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Se a cobrança está em modo de desenvolvimento",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Pedido associado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abacatepay_billing",
                        to="orders.order",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Cliente que fez a cobrança",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billings",
                        to="payments.abacatepaycustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cobrança AbacatePay",
                "verbose_name_plural": "Cobranças AbacatePay",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbacatePayPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(
                        blank=True, help_text="URL para pagamento", max_length=500
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor pago",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                            ("FAILED", "Falhou"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="Status do pagamento",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PIX", "PIX"),
                            ("CARD", "Cartão de Crédito"),
                            ("BOLETO", "Boleto"),
                        ],
                        help_text="Método de pagamento usado",
                        max_length=20,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict, help_text="Resposta completa da API da AbacatePay"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora em que o pagamento foi confirmado",
                        null=True,
                    ),
                ),
                (
                    "billing",
                    models.ForeignKey(
                        help_text="Cobrança associada",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.abacatepaybilling",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Pedido associado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abacatepay_payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pagamento AbacatePay",
                "verbose_name_plural": "Pagamentos AbacatePay",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="abacatepaybilling",
            index=models.Index(
                fields=["billing_id"], name="payments_ab_billing_7bdae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abacatepaybilling",
            index=models.Index(fields=["status"], name="payments_ab_status_4b2f7c_idx"),
        ),
        migrations.AddIndex(
            model_name="abacatepaybilling",
            index=models.Index(
                fields=["customer"], name="payments_ab_custome_fbdaf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abacatepaypayment",
            index=models.Index(
                fields=["billing"], name="payments_ab_billing_6a9e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abacatepaypayment",
            index=models.Index(fields=["status"], name="payments_ab_status_fde316_idx"),
        ),
        migrations.AddIndex(
            model_name="abacatepaypayment",
            index=models.Index(fields=["order"], name="payments_ab_order_i_777f04_idx"),
        ),
    ]
