# Generated by Django 5.2.9 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultPricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bar_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["bar_value"],
                "indexes": [
                    models.Index(
                        fields=["bar_value"], name="legacy_defa_bar_val_23ebe2_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("last_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_offers", models.IntegerField()),
                ("price_history", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="legacy_item_slug_654c17_idx")
                ],
            },
        ),
    ]
