# Generated by Django 5.2.6 on 2025-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
