# Generated by Django 5.2.9 on 2026-01-15 17:36

import legacy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, unique=True, validators=[legacy.models.FlexibleSlugValidator()]),
        ),
    ]
