# Generated by Django 5.2.6 on 2025-12-25 02:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF no formato XXX.XXX.XXX-XX",
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    accounts.models.OptionalRegexValidator(
                        message="CPF deve estar no formato XXX.XXX.XXX-XX",
                        regex="^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telefone",
            field=models.CharField(
                blank=True,
                help_text="Telefone no formato (XX) XXXXX-XXXX",
                max_length=15,
                null=True,
                validators=[
                    accounts.models.OptionalRegexValidator(
                        message="Telefone deve estar no formato (XX) XXXXX-XXXX",
                        regex="^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                help_text="Endereço da carteira MetaMask",
                max_length=42,
                null=True,
                unique=True,
                validators=[
                    accounts.models.OptionalRegexValidator(
                        message="Endereço da carteira deve ser um endereço Ethereum válido",
                        regex="^0x[a-fA-F0-9]{40}$",
                    )
                ],
            ),
        ),
    ]
