"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from urllib.parse import urlparse
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "t")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Local apps
    "accounts",
    "banners",
    "orders",
    "payments",
    # Installed apps
    "rest_framework",
    "django_filters",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    # "gallery",
    "nft",
    "legacy",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

USE_POSTGRES = os.getenv("USE_POSTGRES", "False").lower() in ("true", "1", "t")

if not USE_POSTGRES:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "localhost"),
            "PORT": os.getenv("POSTGRES_PORT", "5433"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Efficient static file serving in production (Django 5+ STORAGES)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

FRONTEND_ORIGINS = [
    o.strip() for o in os.getenv("FRONTEND_ORIGINS", "").split(",") if o.strip()
]
API_ORIGIN = os.getenv("API_ORIGIN")  # e.g. https://api.nftmarketplace.com.br

if FRONTEND_ORIGINS:
    CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
else:
    # fallback for dev
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = []
for origin in FRONTEND_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(origin)
if API_ORIGIN:
    CSRF_TRUSTED_ORIGINS.append(API_ORIGIN)

# If ALLOWED_HOSTS was not explicitly configured for production, augment it with hosts
# parsed from FRONTEND_ORIGINS and API_ORIGIN to reduce misconfiguration 400s.
if not os.getenv("ALLOWED_HOSTS"):
    derived_hosts: list[str] = []
    for origin in FRONTEND_ORIGINS + ([API_ORIGIN] if API_ORIGIN else []):
        try:
            host = urlparse(origin).hostname
            if host:
                derived_hosts.append(host)
        except Exception:
            pass
    # Merge and de-duplicate
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + derived_hosts))

# Configure token lifetimes for Simple JWT
# If tokens are expiring too quickly (or if there is small clock drift between services),
# increase ACCESS_TOKEN_LIFETIME and REFRESH_TOKEN_LIFETIME as appropriate for your dev environment.
SIMPLE_JWT = {
    # Access tokens valid for 1 hour (adjust as needed)
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    # Refresh tokens valid for 7 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}
# DRF Configuration
# See: https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",  # Only for development
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}

# Spectacular settings
# See: https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    "TITLE": "NFT Portal API",
    "DESCRIPTION": "API do NFT Portal",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# Email configuration - Gmail SMTP
# See: https://docs.djangoproject.com/en/5.2/topics/email/
# Para usar Gmail, você precisa:
# 1. Habilitar "Acesso a apps menos seguros" OU
# 2. Usar uma "Senha de app" (recomendado): https://support.google.com/accounts/answer/185833
# 3. Configurar as variáveis no .env:
#    - EMAIL_HOST_USER=seu-email@gmail.com
#    - EMAIL_HOST_PASSWORD=sua-senha-de-app
#    - DEFAULT_FROM_EMAIL=seu-email@gmail.com
#    - ADMIN_EMAIL=admin@example.com (opcional)

# Verifica se as credenciais de email estão configuradas
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()

# Se não estiverem configuradas, usa console backend (para desenvolvimento)
if not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    # Usar print para garantir que apareça no console do Docker
    print(
        f"[EMAIL CONFIG] EMAIL_HOST_USER ou EMAIL_HOST_PASSWORD não configurados. "
        f"EMAIL_HOST_USER={'vazio' if not EMAIL_HOST_USER else 'configurado'}, "
        f"EMAIL_HOST_PASSWORD={'vazio' if not EMAIL_HOST_PASSWORD else 'configurado'}. "
        f"Usando console backend para emails (emails serão exibidos no console)."
    )
    import logging

    logger = logging.getLogger(__name__)
    logger.warning(
        f"EMAIL_HOST_USER ou EMAIL_HOST_PASSWORD não configurados. "
        f"EMAIL_HOST_USER={'vazio' if not EMAIL_HOST_USER else 'configurado'}, "
        f"EMAIL_HOST_PASSWORD={'vazio' if not EMAIL_HOST_PASSWORD else 'configurado'}. "
        f"Usando console backend para emails (emails serão exibidos no console)."
    )
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # Define valores padrão para evitar erros
    EMAIL_HOST = "localhost"
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False
    EMAIL_TIMEOUT = 10
    DEFAULT_FROM_EMAIL = os.getenv(
        "DEFAULT_FROM_EMAIL", "noreply@nftmarketplace.com.br"
    )
    ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", DEFAULT_FROM_EMAIL)
else:
    # Usar print para garantir que apareça no console do Docker
    email_display = (
        f"{EMAIL_HOST_USER[:3]}***@{EMAIL_HOST_USER.split('@')[1]}"
        if "@" in EMAIL_HOST_USER
        else "unknown"
    )
    print(
        f"[EMAIL CONFIG] Configuração de email SMTP detectada. "
        f"EMAIL_HOST_USER={email_display}, EMAIL_HOST={os.getenv('EMAIL_HOST', 'smtp.gmail.com')}, "
        f"EMAIL_PORT={os.getenv('EMAIL_PORT', '587')}"
    )
    import logging

    logger = logging.getLogger(__name__)
    logger.info(
        f"Configuração de email SMTP detectada. " f"EMAIL_HOST_USER={email_display}"
    )
    # Configuração SMTP para Gmail
    EMAIL_BACKEND = os.getenv(
        "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
    )

    # Gmail SMTP Configuration
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("true", "1", "t")
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() in ("true", "1", "t")

    # Validação: verificar se o email é um Gmail (opcional, apenas aviso)
    if (
        EMAIL_HOST == "smtp.gmail.com"
        and "@gmail.com" not in EMAIL_HOST_USER
        and "@googlemail.com" not in EMAIL_HOST_USER
    ):
        print(
            f"[EMAIL CONFIG] ⚠ AVISO: EMAIL_HOST_USER ({EMAIL_HOST_USER}) não parece ser um Gmail. "
            f"Para usar smtp.gmail.com, você precisa de um email @gmail.com ou @googlemail.com"
        )

    # Email padrão para envio
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
    # Email para notificações de admin
    ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", DEFAULT_FROM_EMAIL)

    # Timeout para conexões SMTP (em segundos)
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

# Configurações adicionais para Gmail
EMAIL_SUBJECT_PREFIX = os.getenv("EMAIL_SUBJECT_PREFIX", "[NFT Portal] ")

# Secure proxy headers for correct HTTPS detection behind nginx
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# Cookie security in production
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"

# Celery Configuration
# See: https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 30

# Configurações de Timezone para Celery
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = False  # Usar timezone local em vez de UTC
CELERY_USE_TZ = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_EXPIRES = 3600

# Configuração para usar crontab para horário específico
from celery.schedules import crontab  # noqa: E402

# Configurações de Agendamento (Beat Schedule)
CELERY_BEAT_SCHEDULE = {
    # Atualização de preços dos NFTs - Todo dia às 3h da manhã (sequencial, um item a cada 3.5s)
    "update-all-nft-prices-3am": {
        "task": "nft.tasks.update_all_nft_prices_sequential",
        "schedule": crontab(hour=3, minute=0),  # Executa diariamente às 3h00
        "options": {
            "expires": 60 * 60 * 4,  # Expira em 4 horas se não executar
        },
    },
    # Limpeza semanal de dados antigos
    "cleanup-old-data": {
        "task": "nft.tasks.cleanup_old_price_updates",
        "schedule": 60.0 * 60.0 * 24.0 * 7.0,  # Executa a cada 7 dias
        "options": {
            "expires": 60 * 60 * 24,  # Expira em 24 horas se não executar
        },
    },
    # Rotina de segurança: verifica pedidos não pagos a cada 30 minutos
    "cancel-unpaid-orders-security": {
        "task": "orders.tasks.cancel_unpaid_orders_security_check",
        "schedule": 60.0 * 30.0,  # Executa a cada 30 minutos
        "options": {
            "expires": 60 * 60,  # Expira em 1 hora se não executar
        },
    },
    # Sincronização de novos NFTs da SecureHabbo - Todo dia às 2h da manhã
    "sync-securehabbo-nfts-2am": {
        "task": "nft.tasks.sync_new_nfts_from_securehabbo_task",
        "schedule": crontab(hour=2, minute=0),  # Executa diariamente às 2h00
        "options": {
            "expires": 60 * 60 * 4,  # Expira em 4 horas se não executar
        },
    },
}

# Auth User Model
AUTH_USER_MODEL = "accounts.User"

# AbacatePay Configuration
ABACATEPAY_API_BASE_URL = os.getenv("ABACATEPAY_API_BASE_URL")
ABACATEPAY_API_KEY = os.getenv("ABACATEPAY_API_KEY", "")
# Chave pública HMAC da AbacatePay (conforme documentação oficial)
# Esta é uma chave pública compartilhada, não é secreta
# Chave pública HMAC da AbacatePay
# IMPORTANTE: Remover espaços e quebras de linha que podem ter sido adicionados acidentalmente
_abacatepay_public_key_raw = os.getenv(
    "ABACATEPAY_PUBLIC_KEY",
    "t9dXRhHHo3yDEj5pVDYz0frf7q6bMKyMRmxxCPIPp3RCplBfXRxqlC6ZpiWmOqj4L63qEaeUOtrCI8P0VMUgo6iIga2ri9ogaHFs0WIIywSMg0q7RmBfybe1E5XJcfC4IW3alNqym0tXoAKkzvfEjZxV6bE0oG2zJrNNYmUCKZyV0KZ3JS8Votf9EAWWYdiDkMkpbMdPggfh1EqHlVkMiTady6jOR3hyzGEHrIz2Ret0xHKMbiqkr9HS1JhNHDX9",
)
# Remove espaços em branco e quebras de linha
ABACATEPAY_PUBLIC_KEY = (
    _abacatepay_public_key_raw.strip().replace("\n", "").replace("\r", "")
    if _abacatepay_public_key_raw
    else ""
)
ABACATEPAY_WEBHOOK_SECRET = os.getenv("ABACATEPAY_WEBHOOK_SECRET", "")
ABACATEPAY_DOCS_URL = os.getenv("ABACATEPAY_DOCS_URL", "https://docs.abacatepay.com")
