# Generated by Django 5.2.9 on 2026-01-14 14:07

import django.db.models.deletion
import nft.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "global_markup_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Markup padrão aplicado em todos os preços quando o item não tem override (ex.: 30.00 = +30%).",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Preço",
                "verbose_name_plural": "Configurações de Preço",
            },
        ),
        migrations.CreateModel(
            name="NftCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome da Coleção"),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[nft.models.validate_eth_address],
                        verbose_name="Endereço do Contrato",
                    ),
                ),
                (
                    "profile_image",
                    models.URLField(blank=True, verbose_name="Foto de Perfil"),
                ),
                (
                    "cover_image",
                    models.URLField(blank=True, verbose_name="Foto de Capa"),
                ),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do criador (caso não seja um usuário registrado)",
                        max_length=150,
                        verbose_name="Nome do Criador",
                    ),
                ),
                (
                    "items_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de NFTs nesta coleção",
                        verbose_name="Número de Itens",
                    ),
                ),
                (
                    "owners_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de proprietários únicos",
                        verbose_name="Número de Proprietários",
                    ),
                ),
                (
                    "floor_price",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Menor preço listado na coleção",
                        max_digits=20,
                        verbose_name="Floor Price (ETH)",
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Volume total negociado",
                        max_digits=30,
                        verbose_name="Volume Total (ETH)",
                    ),
                ),
                (
                    "metadata_api_url",
                    models.URLField(blank=True, verbose_name="URL da API de Metadados"),
                ),
                ("project_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "project_owner_address",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        validators=[nft.models.validate_eth_address],
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Site Oficial"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="X (Twitter)"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("discord_url", models.URLField(blank=True, verbose_name="Discord")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nft_created_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NFTItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=120)),
                ("blueprint", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "name_pt_br",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="Nome (pt-BR)",
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=80)),
                ("is_crafted_item", models.BooleanField(db_index=True, default=False)),
                (
                    "is_craft_material",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("rarity", models.CharField(blank=True, db_index=True, max_length=80)),
                (
                    "item_type",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "item_sub_type",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("number", models.IntegerField(blank=True, null=True)),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=120, null=True, unique=True
                    ),
                ),
                ("product_type", models.CharField(blank=True, max_length=120)),
                ("material", models.CharField(blank=True, max_length=120)),
                (
                    "last_price_eth",
                    models.DecimalField(
                        blank=True, decimal_places=18, max_digits=38, null=True
                    ),
                ),
                (
                    "last_price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "last_price_brl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentual de markup específico para este item (ex.: 30.00 = +30%). Se vazio, usa o global.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "seven_day_volume_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("seven_day_sales_count", models.IntegerField(default=0)),
                (
                    "seven_day_avg_price_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "seven_day_last_sale_brl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "seven_day_price_change_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=7, null=True
                    ),
                ),
                ("seven_day_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="nft.nftcollection",
                        verbose_name="Coleção",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "rarity", "item_type", "item_sub_type"],
            },
        ),
        migrations.CreateModel(
            name="NFTItemAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_hash", models.CharField(blank=True, default="", max_length=64)),
                (
                    "user_agent_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="nft.nftitem",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="nftcollection",
            index=models.Index(fields=["slug"], name="nft_nftcoll_slug_b27bbd_idx"),
        ),
        migrations.AddIndex(
            model_name="nftcollection",
            index=models.Index(
                fields=["address"], name="nft_nftcoll_address_667d35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(fields=["source"], name="nft_nftitem_source_7be38d_idx"),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(fields=["rarity"], name="nft_nftitem_rarity_6db5be_idx"),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(
                fields=["item_type"], name="nft_nftitem_item_ty_e162ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(
                fields=["item_sub_type"], name="nft_nftitem_item_su_6daded_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(
                fields=["is_crafted_item"], name="nft_nftitem_is_craf_6d4eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(
                fields=["is_craft_material"], name="nft_nftitem_is_craf_691fcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(fields=["name"], name="nft_nftitem_name_709a2e_idx"),
        ),
        migrations.AddIndex(
            model_name="nftitem",
            index=models.Index(
                fields=["product_code"], name="nft_nftitem_product_32628b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitemaccess",
            index=models.Index(
                fields=["accessed_at"], name="nft_nftitem_accesse_9967d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nftitemaccess",
            index=models.Index(
                fields=["item", "accessed_at"], name="nft_nftitem_item_id_139312_idx"
            ),
        ),
    ]
