# Generated by Django 5.2.9 on 2026-01-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nftitem",
            options={
                "ordering": ["name", "rarity", "item_type", "item_sub_type"],
                "verbose_name": "NFT Item",
                "verbose_name_plural": "NFT Items",
            },
        ),
    ]
