# Generated by Django 5.2.6 on 2025-10-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0004_pricing_config_and_item_markup"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_source_7be38d_idx",
            old_name="nft_item_source_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_rarity_6db5be_idx",
            old_name="nft_item_rarity_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_item_ty_e162ab_idx",
            old_name="nft_item_item_type_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_item_su_6daded_idx",
            old_name="nft_item_item_sub_type_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_is_craf_6d4eef_idx",
            old_name="nft_item_is_crafted_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_is_craf_691fcf_idx",
            old_name="nft_item_is_material_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_name_709a2e_idx",
            old_name="nft_item_name_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitem",
            new_name="nft_nftitem_product_32628b_idx",
            old_name="nft_item_product_code_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitemaccess",
            new_name="nft_nftitem_accesse_9967d6_idx",
            old_name="nft_accessed_at_idx",
        ),
        migrations.RenameIndex(
            model_name="nftitemaccess",
            new_name="nft_nftitem_item_id_139312_idx",
            old_name="nft_item_access_idx",
        ),
    ]
