# Generated by Django 5.2.6 on 2025-12-25 02:16

import django.db.models.deletion
import nft.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nft", "0006_add_name_pt_br"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NftCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nome da Coleção"),
                ),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "address",
                    models.CharField(
                        max_length=42,
                        unique=True,
                        validators=[nft.models.validate_eth_address],
                        verbose_name="Endereço do Contrato",
                    ),
                ),
                (
                    "profile_image",
                    models.URLField(blank=True, verbose_name="Foto de Perfil"),
                ),
                (
                    "cover_image",
                    models.URLField(blank=True, verbose_name="Foto de Capa"),
                ),
                (
                    "creator_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do criador (caso não seja um usuário registrado)",
                        max_length=150,
                        verbose_name="Nome do Criador",
                    ),
                ),
                (
                    "items_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de NFTs nesta coleção",
                        verbose_name="Número de Itens",
                    ),
                ),
                (
                    "owners_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total de proprietários únicos",
                        verbose_name="Número de Proprietários",
                    ),
                ),
                (
                    "floor_price",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Menor preço listado na coleção",
                        max_digits=20,
                        verbose_name="Floor Price (ETH)",
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Volume total negociado",
                        max_digits=30,
                        verbose_name="Volume Total (ETH)",
                    ),
                ),
                (
                    "metadata_api_url",
                    models.URLField(blank=True, verbose_name="URL da API de Metadados"),
                ),
                ("project_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "project_owner_address",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        validators=[nft.models.validate_eth_address],
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, verbose_name="Site Oficial"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, verbose_name="X (Twitter)"),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("discord_url", models.URLField(blank=True, verbose_name="Discord")),
                ("telegram_url", models.URLField(blank=True, verbose_name="Telegram")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nft_created_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criador",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="nft_nftcoll_slug_b27bbd_idx"),
                    models.Index(
                        fields=["address"], name="nft_nftcoll_address_667d35_idx"
                    ),
                ],
            },
        ),
    ]
